#!/usr/bin/env python

import subprocess
import sys

device_to_use = 'TV'

if len(sys.argv) > 1:
  device_to_use = sys.argv[1]
  print 'Switching to '+device_to_use

p = subprocess.Popen(['listsinks'], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
out, err = p.communicate()

lines = out.split('\n')

DEVICE_TV = 'device.description = "Built-in Audio Digital Stereo (HDMI)"'
DEVICE_BEDROOM = 'device.description = "Built-in Audio Analog Stereo"'

if device_to_use == 'TV':
  DEVICE_CODE = DEVICE_TV
else:
  DEVICE_CODE = DEVICE_BEDROOM

line_num = 0
for line in lines:
  #print line
  if DEVICE_CODE in line:
    index_line = lines[line_num-1]
    index = index_line[11:12].strip()
    print 'Device has index '+index
    
  line_num = line_num + 1
  
p = subprocess.Popen(['movesinks', index], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
out, err = p.communicate()