#!/bin/bash

if [ -z "$3" ]; then
  SLIDEDIR='/media/jason/e/documents/wallpapers/slide/'
else
  SLIDEDIR=$3'/'
fi

if [ -z "$2" ]; then
  DOMAIN='/media/jason/e/documents/wallpapers/'
else
  DOMAIN=$2'/'
fi

if [ $1 == "rand" ]; then
  FILENAME=$(find $DOMAIN -maxdepth 1 -type f | sort -R | tail -1)
  FILENAME=$(basename $FILENAME)
  FILENAME=${FILENAME:0:-6}
else
  FILENAME=$1
fi

echo 'Changing to '$FILENAME' now!'

cp $DOMAIN$FILENAME'-L.jpg' $SLIDEDIR'L/L.jpg'
cp $DOMAIN$FILENAME'-R.jpg' $SLIDEDIR'R/R.jpg'
