#!/bin/bash

usage()
{
cat << EOF
usage: $0 options

VIDEO-THUMB: Generate video thumbnail

OPTIONS:
   -h, --help             Show this message
   -i, --input            Input file. Can be a wide variety of formats, try 'avconv -formats' to see a list.
   -o, --output           Output file.
   -v, --verbose          Verbose output.
   
   
EOF
exit 0
}

INPUT=
OUTPUT="default"
VERBOSE=false

params="$(getopt -o hvi:o: -l help,verbose,input:output: --name "$0" -- "$@")"
eval set -- "$params"

while true
do
    case "$1" in
        -h|--help)
            usage
            break
            ;;
        -i|--input)
            INPUT=$2
            shift 2
            ;;
        -o|--output)
            OUTPUT=$2
            shift 2
            ;;
        -v|--verbose)
            VERBOSE=true
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            echo "Not implemented: $1" >&2
            exit 1
            ;;
    esac
done

if [ "$OUTPUT" = "default" ] ; then
  OUTPUT="$FILENAME-thumb.png"
fi


if $VERBOSE
then
	echo "VIDEO-THUMBS: Starting..."
fi

DURATION_HMS=$(avconv -i "$INPUT" 2>&1 | grep Duration | cut -f 4 -d ' ')
DURATION_H=$(echo "$DURATION_HMS" | cut -d ':' -f 1)
DURATION_M=$(echo "$DURATION_HMS" | cut -d ':' -f 2)
DURATION_S=$(echo "$DURATION_HMS" | cut -d ':' -f 3 | cut -d '.' -f 1)
let "DURATION = ( 10#$DURATION_H * 60 + 10#$DURATION_M ) * 60 + 10#$DURATION_S"
let "START = ( $DURATION / 2 )"
 
if [ "$DURATION" = '0' ] ; then
        echo "Invalid input video"
        usage
        exit 1
fi

FILENAME=$(basename "$INPUT")
EXTENSION="${FILENAME##*.}"
FILENAME="${FILENAME%.*}"

if $VERBOSE
then
	avconv -ss $START -i $INPUT -r 1 -vsync 1 -an $OUTPUT
else
	avconv -ss $START -i $INPUT -r 1 -vsync 1 -an $OUTPUT -loglevel 'quiet' > /dev/null
fi

if $VERBOSE
then
	echo "VIDEO-THUMBS: Done!"
fi

exit 0

